FreeBSD: { enabled: no }
FreeBSD-kmods: { enabled: no }

%%PRODUCT_NAME%%: {
  url: "%%PKG_REPO_SERVER_RELEASE%%/%%PRODUCT_NAME%%_%%POUDRIERE_BRANCH%%_%%ARCH%%-%%POUDRIERE_PORTS_NAME%%",
  mirror_type: "%%MIRROR_TYPE%%",
  signature_type: "%%SIGNATURE_TYPE%%",
  fingerprints: "/usr/local/share/%%PRODUCT_NAME%%/keys/pkg",
  enabled: yes
}
